// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/account/account.proto

package onestory_account_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FullAccount struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	OpenId               string   `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	PassId               string   `protobuf:"bytes,3,opt,name=PassId,proto3" json:"PassId,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone                int32    `protobuf:"varint,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	NickName             string   `protobuf:"bytes,7,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Avatar               string   `protobuf:"bytes,8,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Ext                  string   `protobuf:"bytes,9,opt,name=Ext,proto3" json:"Ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullAccount) Reset()         { *m = FullAccount{} }
func (m *FullAccount) String() string { return proto.CompactTextString(m) }
func (*FullAccount) ProtoMessage()    {}
func (*FullAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_38cb24b57095674f, []int{0}
}
func (m *FullAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullAccount.Unmarshal(m, b)
}
func (m *FullAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullAccount.Marshal(b, m, deterministic)
}
func (dst *FullAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullAccount.Merge(dst, src)
}
func (m *FullAccount) XXX_Size() int {
	return xxx_messageInfo_FullAccount.Size(m)
}
func (m *FullAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_FullAccount.DiscardUnknown(m)
}

var xxx_messageInfo_FullAccount proto.InternalMessageInfo

func (m *FullAccount) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FullAccount) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *FullAccount) GetPassId() string {
	if m != nil {
		return m.PassId
	}
	return ""
}

func (m *FullAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *FullAccount) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *FullAccount) GetPhone() int32 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *FullAccount) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *FullAccount) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FullAccount) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

type SafeAccount struct {
	OpenId               string   `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	PassId               string   `protobuf:"bytes,3,opt,name=PassId,proto3" json:"PassId,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone                int32    `protobuf:"varint,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	NickName             string   `protobuf:"bytes,7,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Avatar               string   `protobuf:"bytes,8,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Ext                  string   `protobuf:"bytes,9,opt,name=Ext,proto3" json:"Ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeAccount) Reset()         { *m = SafeAccount{} }
func (m *SafeAccount) String() string { return proto.CompactTextString(m) }
func (*SafeAccount) ProtoMessage()    {}
func (*SafeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_38cb24b57095674f, []int{1}
}
func (m *SafeAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeAccount.Unmarshal(m, b)
}
func (m *SafeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeAccount.Marshal(b, m, deterministic)
}
func (dst *SafeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeAccount.Merge(dst, src)
}
func (m *SafeAccount) XXX_Size() int {
	return xxx_messageInfo_SafeAccount.Size(m)
}
func (m *SafeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SafeAccount proto.InternalMessageInfo

func (m *SafeAccount) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *SafeAccount) GetPassId() string {
	if m != nil {
		return m.PassId
	}
	return ""
}

func (m *SafeAccount) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SafeAccount) GetPhone() int32 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *SafeAccount) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *SafeAccount) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *SafeAccount) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

type RequestQuery struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	PassId               string   `protobuf:"bytes,2,opt,name=PassId,proto3" json:"PassId,omitempty"`
	Phone                int32    `protobuf:"varint,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestQuery) Reset()         { *m = RequestQuery{} }
func (m *RequestQuery) String() string { return proto.CompactTextString(m) }
func (*RequestQuery) ProtoMessage()    {}
func (*RequestQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_38cb24b57095674f, []int{2}
}
func (m *RequestQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestQuery.Unmarshal(m, b)
}
func (m *RequestQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestQuery.Marshal(b, m, deterministic)
}
func (dst *RequestQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestQuery.Merge(dst, src)
}
func (m *RequestQuery) XXX_Size() int {
	return xxx_messageInfo_RequestQuery.Size(m)
}
func (m *RequestQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RequestQuery proto.InternalMessageInfo

func (m *RequestQuery) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *RequestQuery) GetPassId() string {
	if m != nil {
		return m.PassId
	}
	return ""
}

func (m *RequestQuery) GetPhone() int32 {
	if m != nil {
		return m.Phone
	}
	return 0
}

type Request struct {
	Info                 *FullAccount `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_38cb24b57095674f, []int{3}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInfo() *FullAccount {
	if m != nil {
		return m.Info
	}
	return nil
}

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_38cb24b57095674f, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResponseSafe struct {
	Code                 int64        `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *SafeAccount `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResponseSafe) Reset()         { *m = ResponseSafe{} }
func (m *ResponseSafe) String() string { return proto.CompactTextString(m) }
func (*ResponseSafe) ProtoMessage()    {}
func (*ResponseSafe) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_38cb24b57095674f, []int{5}
}
func (m *ResponseSafe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSafe.Unmarshal(m, b)
}
func (m *ResponseSafe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSafe.Marshal(b, m, deterministic)
}
func (dst *ResponseSafe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSafe.Merge(dst, src)
}
func (m *ResponseSafe) XXX_Size() int {
	return xxx_messageInfo_ResponseSafe.Size(m)
}
func (m *ResponseSafe) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSafe.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSafe proto.InternalMessageInfo

func (m *ResponseSafe) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseSafe) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseSafe) GetData() *SafeAccount {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*FullAccount)(nil), "onestory.account.proto.FullAccount")
	proto.RegisterType((*SafeAccount)(nil), "onestory.account.proto.SafeAccount")
	proto.RegisterType((*RequestQuery)(nil), "onestory.account.proto.RequestQuery")
	proto.RegisterType((*Request)(nil), "onestory.account.proto.Request")
	proto.RegisterType((*Response)(nil), "onestory.account.proto.Response")
	proto.RegisterType((*ResponseSafe)(nil), "onestory.account.proto.ResponseSafe")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	InsertAccountInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	UpdateAccountInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetAccountInfo(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseSafe, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) InsertAccountInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/onestory.account.proto.AccountService/InsertAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateAccountInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/onestory.account.proto.AccountService/UpdateAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountInfo(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseSafe, error) {
	out := new(ResponseSafe)
	err := c.cc.Invoke(ctx, "/onestory.account.proto.AccountService/GetAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	InsertAccountInfo(context.Context, *Request) (*Response, error)
	UpdateAccountInfo(context.Context, *Request) (*Response, error)
	GetAccountInfo(context.Context, *RequestQuery) (*ResponseSafe, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_InsertAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).InsertAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.account.proto.AccountService/InsertAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).InsertAccountInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.account.proto.AccountService/UpdateAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateAccountInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.account.proto.AccountService/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountInfo(ctx, req.(*RequestQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onestory.account.proto.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertAccountInfo",
			Handler:    _AccountService_InsertAccountInfo_Handler,
		},
		{
			MethodName: "UpdateAccountInfo",
			Handler:    _AccountService_UpdateAccountInfo_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _AccountService_GetAccountInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/account/account.proto",
}

func init() {
	proto.RegisterFile("grpc/proto/account/account.proto", fileDescriptor_account_38cb24b57095674f)
}

var fileDescriptor_account_38cb24b57095674f = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x27, 0x49, 0xff, 0xe6, 0x16, 0x55, 0x60, 0xa1, 0x91, 0xd5, 0x0d, 0x51, 0x98, 0x45,
	0x57, 0x19, 0x69, 0x58, 0x74, 0x5d, 0xa0, 0xa0, 0x48, 0x50, 0x4a, 0x0a, 0x12, 0x2b, 0x24, 0x93,
	0xdc, 0x96, 0x8a, 0x36, 0x0e, 0xb6, 0x53, 0xe8, 0xfb, 0xb0, 0xe7, 0x81, 0x78, 0x19, 0xe4, 0x9f,
	0xa0, 0x14, 0x51, 0xaa, 0x4a, 0x88, 0x55, 0xee, 0x39, 0x76, 0x3e, 0x9f, 0x6b, 0x5f, 0x08, 0x57,
	0xa2, 0xcc, 0x6e, 0x4a, 0xc1, 0x15, 0xbf, 0x61, 0x59, 0xc6, 0xab, 0x42, 0xd5, 0xdf, 0xd8, 0xb8,
	0xe4, 0x8a, 0x17, 0x28, 0x15, 0x17, 0xfb, 0xf8, 0xc0, 0x8f, 0x7e, 0x78, 0xd0, 0x7f, 0x56, 0x6d,
	0x36, 0x13, 0xeb, 0x92, 0x01, 0xf8, 0x49, 0x4e, 0xbd, 0xd0, 0x1b, 0x05, 0xa9, 0x9f, 0xe4, 0xe4,
	0x0a, 0x3a, 0xaf, 0x4a, 0x2c, 0x92, 0x9c, 0xfa, 0xa1, 0x37, 0xba, 0x4c, 0x9d, 0xd2, 0xfe, 0x9c,
	0x49, 0x99, 0xe4, 0x34, 0xb0, 0xbe, 0x55, 0x64, 0x08, 0x3d, 0x5d, 0x7d, 0xe1, 0x22, 0xa7, 0x2d,
	0xb3, 0xf2, 0x4b, 0x93, 0xfb, 0xd0, 0x9e, 0x6e, 0xd9, 0x7a, 0x43, 0xdb, 0x66, 0xc1, 0x0a, 0xed,
	0xce, 0x3f, 0xf2, 0x02, 0x69, 0x27, 0xf4, 0x46, 0xed, 0xd4, 0x0a, 0xcd, 0x99, 0xad, 0xb3, 0x4f,
	0x33, 0xb6, 0x45, 0xda, 0xb5, 0x9c, 0x5a, 0xeb, 0xb3, 0x27, 0x3b, 0xa6, 0x98, 0xa0, 0x3d, 0x7b,
	0xb6, 0x55, 0xe4, 0x2e, 0x04, 0xd3, 0xaf, 0x8a, 0x5e, 0x1a, 0x53, 0x97, 0xd1, 0x77, 0x0f, 0xfa,
	0x0b, 0xb6, 0xc4, 0xba, 0xbb, 0x73, 0xbb, 0xf9, 0xff, 0x89, 0xdf, 0xc0, 0x9d, 0x14, 0x3f, 0x57,
	0x28, 0xd5, 0xeb, 0x0a, 0xc5, 0xbe, 0x91, 0xd8, 0x3b, 0x92, 0xd8, 0xff, 0x3d, 0xb1, 0xcd, 0x16,
	0x34, 0xb2, 0x45, 0x8f, 0xa1, 0xeb, 0xa8, 0x64, 0x0c, 0xad, 0xa4, 0x58, 0x72, 0x83, 0xeb, 0xdf,
	0x3e, 0x8c, 0xff, 0x3c, 0x17, 0x71, 0x63, 0x26, 0x52, 0xf3, 0x43, 0xf4, 0x02, 0x7a, 0x29, 0xca,
	0x92, 0x17, 0x12, 0x09, 0x81, 0xd6, 0x13, 0x9e, 0xa3, 0x9b, 0x13, 0x53, 0x13, 0x0a, 0xdd, 0x97,
	0x28, 0x25, 0x5b, 0xa1, 0x8b, 0x54, 0x4b, 0xbd, 0xfb, 0x29, 0x53, 0xcc, 0xdd, 0xad, 0xa9, 0xa3,
	0x4a, 0xf7, 0x69, 0x69, 0xfa, 0x81, 0xce, 0x24, 0x8e, 0x1b, 0xc4, 0xbf, 0x34, 0xd1, 0x78, 0x7a,
	0x7b, 0xec, 0xed, 0x37, 0x1f, 0x06, 0xce, 0x59, 0xa0, 0xd8, 0xad, 0x33, 0x24, 0xef, 0xe0, 0x5e,
	0x52, 0x48, 0x14, 0xca, 0xf9, 0xba, 0x59, 0xf2, 0xe0, 0x18, 0xd2, 0x5d, 0xe3, 0x30, 0x3c, 0xbe,
	0xc1, 0x76, 0x15, 0x5d, 0x68, 0xf2, 0xdb, 0x32, 0x67, 0x0a, 0xff, 0x39, 0xf9, 0x3d, 0x0c, 0x9e,
	0xe3, 0x41, 0xe0, 0xeb, 0x13, 0x58, 0x33, 0x4d, 0xc3, 0xeb, 0x53, 0x6c, 0x7d, 0x63, 0xd1, 0xc5,
	0x87, 0x8e, 0x71, 0x1f, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xab, 0xc3, 0xbd, 0x50, 0x58, 0x04,
	0x00, 0x00,
}
